const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * Deploys Voting with a starting ballot, then writes the deployed address + ABI
 * into frontend/src/utils/contract.js so the frontend always points at the
 * latest deployment. (Per AGENTS.md: the #1 cause of "nothing works" is a stale
 * address — automating this removes that footgun.)
 */
async function main() {
  const candidates = ["Alice", "Bob", "Carol"];

  const Voting = await hre.ethers.getContractFactory("Voting");
  const voting = await Voting.deploy(candidates);
  await voting.waitForDeployment();

  const address = await voting.getAddress();
  console.log(`Voting deployed to: ${address}`);
  console.log(`Initial candidates: ${candidates.join(", ")}`);

  writeFrontendConfig(address);
}

function writeFrontendConfig(address) {
  // Pull the ABI from the freshly compiled artifact.
  const artifact = hre.artifacts.readArtifactSync("Voting");

  const outPath = path.join(__dirname, "..", "frontend", "src", "utils", "contract.js");
  const contents =
    `// AUTO-GENERATED by scripts/deploy.js on each deploy. Do not edit by hand —\n` +
    `// re-run the deploy script and this file is rewritten with the new address.\n` +
    `export const CONTRACT_ADDRESS = "${address}";\n\n` +
    `export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};\n`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, contents);
  console.log(`Wrote address + ABI to ${path.relative(process.cwd(), outPath)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
